### ISSUE TITLE
Bug/feature suggestion: Links (v0.0.7)

### ISSUE THREAD

**Issue by Munzu** [tbung/markdown-electron#1]
Right now, when you click on a link in the markdown-electron window, the website will open right in markdown-electron instead of in the browser. This is fine but there is no immediate way to get back to the file; one would have to press Ctrl-O and select the file to get back.
When right-clicking the link, the context menu has the option to "Open in Browser" but that doesn't do anything.

Suggestion:
Keep the feature that websites open in markdown-electron but add a way to go back to the file immediately, like by pressing `Esc` or another shortcut.

**Comment by tbung** [comment]
Fixed in https://github.com/tbung/markdown-electron/commit/d4ce404e4a1c7ba64b1349b80742b98c9ebfb9a3.
