### ISSUE TITLE
Different filepaths for configs for development vs production

### ISSUE THREAD

**Issue by Munzu** [tbung/markdown-electron#2]
When right-clicking in markdown-electron and selecting either of the PhantomJS options (PDF, PNG or JPEG), nothing happens. 
I have verified that PhantomJS is installed on my system.
This is markdown-electron version 0.0.7 installed with the .pacman file on Manjaro Linux.

**Comment by tbung** [comment]
PhantomJS and the context menu are superseded by the menu bar and puppeteer, see https://github.com/tbung/markdown-electron/commit/145829e525481ae6a976d22892e8f81eb064efdf.
